### KoTH Plugin Configuration ###

## How long (in seconds) after the server starts should a Hill be randomly selected? ##
## This value is also the delay for Hill rotation after the active Hill has been claimed ##
HILL_ROTATE_DELAY: 900
## How long (in seconds) should a Player have to stay on the Hill to become King? ##
HILL_CLAIM_DELAY: 600
## Number of seconds between each broadcast of PLAYER_CLAIMING_HILL ##
HILL_CLAIM_BROADCAST: 60

## Inventory for the reward chest spawned when a Player becomes King of a Hill ##
## Item Format: 'MATERIAL:AMOUNT:[DISPLAYNAME]:[LORE1,LORE2]:[ENCHANT/LEVEL]=[%CHANCE]' ## 
## You can use 'none' for no custom value on either DISPLAYNAME, LORE or ENCHANT ##
## The chance value is out of 100. If no chance is specified the chance defaults to 100 ##
## Material values can be found here: http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html ##
## Enchantment values can be found here: http://jd.bukkit.org/rb/apidocs/org/bukkit/enchantments/Enchantment.html ##
CHEST_LOADOUT:
- 'DIRT:64'
- 'DIAMOND:1=50'
- 'DIAMOND:1:&bSpecial Diamond=35'
- 'DIAMOND:1:&cSuper Diamond:none:LUCK/1=20'

### KoTH Plugin Message Configuration ###

## Configuration for Messages sent to a single Player ## 
## Use ChatColor codes in addition to an '&' sign for color ##
messages:

  # Prefix added to all Player messages sent by the plugin #
  PREFIX: '&7[&cKoTH&7]&r'
  
  # Message sent when a Player starts claiming a Hill #
  PLAYER_CLAIMING_HILL: '&aYou are now claiming this Hill! Stay on the &cred &awool for 10 minutes to become King!'
  # Message sent when a Player becomes King of a Hill #
  # %hill% = the display name of the claimed Hill #
  PLAYER_CLAIMED_HILL: '&aYou have successfully claimed %hill%&a! A reward Chest has been spawned at the Hill!'
  # Message sent when a Player tries to open a Hill's reward chest without being the King #
  PLAYER_NOT_KING: '&cThis chest can only be opened by the King of this Hill!'
 
## Configuration for Messages broadcasted to the server ## 
## Use ChatColor codes in addition to an '&' sign for color ## 
broadcasts:

  # Prefix added to all Broadcast messages sent by the plugin #
  PREFIX: '&l&7[&4KoTH&l&7]&r'
  
  # Broadcast sent when a random Hill becomes active #
  # %hill% = the display name of the active Hill #
  # %coords% = the coordinates of the active Hill #
  HILL_ACTIVE: '%hill% &ais now active! Get to &e%coords% &ato claim the Hill!'
  # Broadcast sent every time a Player holds a Hill for another minute #
  # %hill% = the display name of the active Hill #
  # %coords% = the coordinates of the active Hill #
  # %player% = the Player claiming the active Hill #
  PLAYER_CLAIMING_HILL: '%hill% &ais being claimed by &e%player%&a! Stop them!'
  # Broadcast message sent when a Player becomes King of a Hill #
  # %hill% = the display name of the claimed Hill #
  # %player% = the king Player's name # 
  PLAYER_CLAIMED_HILL: '%hill% &ahas been claimed by &e%player%&a!'